// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAisUGCCVCOJ91tcXSV3DtTJMfsq_bdXmE',
    appId: '1:970161596305:web:1b522161b2124981441c30',
    messagingSenderId: '970161596305',
    projectId: 'jochat',
    authDomain: 'jochat-ea666.firebaseapp.com',
    databaseURL: 'https://jochat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jochat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL8H_LxZThvBOE9UeB4JeDJb-MrKPaefE',
    appId: '1:970161596305:android:9e9bff5497f1b63a441c30',
    messagingSenderId: '970161596305',
    projectId: 'jochat',
    databaseURL: 'https://jochat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jochat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcaSEYogDzsAXcFCnRQj1cCbYgOWvvtWg',
    appId: '1:970161596305:ios:706b0361243eb102441c30',
    messagingSenderId: '970161596305',
    projectId: 'jochat',
    databaseURL: 'https://jochat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jochat.appspot.com',
    iosClientId: '970161596305-i9n6i0fnovui2g5k9ut3mlsc19mkjldo.apps.googleusercontent.com',
    iosBundleId: 'com.example.jochat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcaSEYogDzsAXcFCnRQj1cCbYgOWvvtWg',
    appId: '1:970161596305:ios:706b0361243eb102441c30',
    messagingSenderId: '970161596305',
    projectId: 'jochat',
    databaseURL: 'https://jochat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jochat.appspot.com',
    iosClientId: '970161596305-i9n6i0fnovui2g5k9ut3mlsc19mkjldo.apps.googleusercontent.com',
    iosBundleId: 'com.example.jochat',
  );
}
